version: '3.1'
services:
    dash-web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        entrypoint: "./entrypoint.sh"
        depends_on:
            - dash-db
        restart: on-failure

    dash-migration:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/app
        entrypoint: "./seed/scripts/seeder.sh"
        depends_on:
            - dash-db
        restart: on-failure

    dash-db:
        image: "postgres:10.13"
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: dash
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
          - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
