"""update vif_num

Revision ID: 018f7ac7fd8c
Revises: 0cd3c05b8a5d
Create Date: 2020-10-03 07:41:54.718564

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '018f7ac7fd8c'
down_revision = '0cd3c05b8a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_model_styles', sa.Column('vif_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'vehicle_model_styles', type_='unique')
    op.drop_column('vehicle_model_styles', 'vif_num')
    # ### end Alembic commands ###
