"""user shoud be nullable

Revision ID: 0cd3c05b8a5d
Revises: 5047c3960ba0
Create Date: 2020-09-13 22:35:55.793806

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0cd3c05b8a5d'
down_revision = '5047c3960ba0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'current_owner_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'current_owner_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###
