"""init base models

Revision ID: 5047c3960ba0
Revises: 
Create Date: 2020-09-10 18:34:22.671987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5047c3960ba0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('token_id', sa.String(length=32), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token_id')
                    )
    op.create_table('core_provider_i18n_links',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('countries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('code', sa.String(length=512), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('locales',
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('id', sa.String(length=2), nullable=False),
                    sa.Column('is_default', sa.Boolean(), nullable=True),
                    sa.Column('english_name', sa.String(length=10), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('media_providers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('permissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('display_name', sa.String(length=128), nullable=False),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['permissions.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('regions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('code', sa.String(length=512), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('display_name', sa.String(length=128), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('tenants',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=True),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('name_url', sa.String(length=512), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('name_url')
                    )
    op.create_table('vehicle_attributes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('parent_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['parent_id'], ['vehicle_attributes.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('vehicle_bodies',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('vehicle_brands',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('vehicle_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('vehicle_drive_trains',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('vehicle_engines',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('label', sa.String(length=256), nullable=True),
                    sa.Column('horse_power', sa.Integer(), nullable=True),
                    sa.Column('torque', sa.Integer(), nullable=True),
                    sa.Column('type', sa.Enum('OTHERS', 'GAS', 'DIESEL', 'ELECTRIC', name='enginetype'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_gallery_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('type',
                              sa.Enum('COVER', 'INTERIOR', 'INTERIOR_COLOR', 'EXTERIOR', 'EXTERIOR_COLOR', 'BRAND_LOGO',
                                      'MODEL_AVATAR', 'YEAR_MODEL_AVATAR', 'VIDEO_INTRODUCTION', 'MODEL_STYLE_AVATAR',
                                      'OPTION_ITEM_AVATAR', 'VEHICLE_AVATAR', 'OTHERS', name='vehiclegalleryitemtype'),
                              nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.Column('asset_path', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_infos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('city_mpg', sa.Integer(), nullable=True),
                    sa.Column('combined_mpg', sa.Integer(), nullable=True),
                    sa.Column('highway_mpg', sa.Integer(), nullable=True),
                    sa.Column('safety_rate', sa.Integer(), nullable=True),
                    sa.Column('doors', sa.Integer(), nullable=True),
                    sa.Column('seats', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_option_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('is_popular', sa.Boolean(), nullable=True),
                    sa.Column('type', sa.Enum('INTERIOR_COLOR', 'EXTERIOR_COLOR', 'PACKAGE', 'OPTION', 'OTHERS',
                                              name='vehicleoptiongrouptype'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_transmissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('label', sa.String(length=256), nullable=True),
                    sa.Column('speeds', sa.Integer(), nullable=True),
                    sa.Column('type', sa.Enum('OTHERS', 'AUTOMATIC', 'MANUAL', name='transmissiontype'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('core_provider_i18n',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('localizable_text_id', sa.Integer(), nullable=False),
                    sa.Column('display_text', sa.String(length=64), nullable=True),
                    sa.Column('locale_id', sa.String(length=2), nullable=False),
                    sa.ForeignKeyConstraint(['locale_id'], ['locales.id'], ),
                    sa.ForeignKeyConstraint(['localizable_text_id'], ['core_provider_i18n_links.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('media_resources',
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('public_id', sa.String(length=256), nullable=False),
                    sa.Column('provider_id', sa.Integer(), nullable=True),
                    sa.Column('format', sa.String(length=10), nullable=True),
                    sa.ForeignKeyConstraint(['provider_id'], ['media_providers.id'], ),
                    sa.PrimaryKeyConstraint('public_id')
                    )
    op.create_table('price_option_assignments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('value_in_cent', sa.Integer(), nullable=True),
                    sa.Column('vehicle_option_item_id', sa.Integer(), nullable=False),
                    sa.Column('region_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_option_item_id'], ['vehicle_option_items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('role_permissions',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('permission_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('role_id', 'permission_id')
                    )
    op.create_table('states',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('code', sa.String(length=512), nullable=True),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.Column('region_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('email', sa.String(length=256), nullable=True),
                    sa.Column('password', sa.String(length=128), nullable=True),
                    sa.Column('full_name', sa.String(length=128), nullable=True),
                    sa.Column('phone_number', sa.String(length=32), nullable=True),
                    sa.Column('address', sa.String(length=1024), nullable=True),
                    sa.Column('title', sa.String(length=256), nullable=True),
                    sa.Column('google_id', sa.String(length=128), nullable=True),
                    sa.Column('facebook_id', sa.String(length=128), nullable=True),
                    sa.Column('type', sa.Enum('HOST', 'TENANT', 'EXTERNAL', name='usertype'), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('vehicle_attribute_values',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('value', sa.String(), nullable=False),
                    sa.Column('value_in_number', sa.Float(), nullable=True),
                    sa.Column('vehicle_attribute_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_attribute_id'], ['vehicle_attributes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_brand_galleries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_brand_id', sa.Integer(), nullable=True),
                    sa.Column('gallery_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gallery_item_id'], ['vehicle_gallery_items.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_brand_id'], ['vehicle_brands.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_models',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('vehicle_brand_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_brand_id'], ['vehicle_brands.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_option_item_galleries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_option_item_id', sa.Integer(), nullable=True),
                    sa.Column('gallery_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gallery_item_id'], ['vehicle_gallery_items.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_option_item_id'], ['vehicle_option_items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_warranties',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_info_id', sa.Integer(), nullable=True),
                    sa.Column('comprehensive', sa.String(), nullable=True),
                    sa.Column('power_train', sa.String(), nullable=True),
                    sa.Column('anti_corrosion', sa.String(), nullable=True),
                    sa.Column('paint', sa.String(), nullable=True),
                    sa.Column('roadside_assistance', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['vehicle_info_id'], ['vehicle_infos.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('cities',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('lat', sa.Float(), nullable=True),
                    sa.Column('long', sa.Float(), nullable=True),
                    sa.Column('state_id', sa.Integer(), nullable=True),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
                    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('reset_tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('token', sa.String(length=6), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('expire', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    op.create_table('sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('token', sa.String(length=32), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('token')
                    )
    op.create_table('vehicle_model_galleries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_id', sa.Integer(), nullable=True),
                    sa.Column('gallery_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gallery_item_id'], ['vehicle_gallery_items.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_year_models',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('vehicle_model_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_models.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('addresses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('raw', sa.String(length=2048), nullable=True),
                    sa.Column('zip_code', sa.Integer(), nullable=True),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.Column('state_id', sa.Integer(), nullable=True),
                    sa.Column('country_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
                    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
                    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('raw')
                    )
    op.create_table('vehicle_model_styles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=256), nullable=False),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=False),
                    sa.Column('include_feature_description', sa.String(), nullable=True),
                    sa.Column('style_features', postgresql.ARRAY(sa.String()), nullable=True),
                    sa.Column('standard_feature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('technical_feature', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('consumer_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('base_MSRP', sa.Float(), nullable=True),
                    sa.Column('manufacture_code', sa.String(), nullable=True),
                    sa.Column('image_url', sa.String(), nullable=True),
                    sa.Column('body_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['body_id'], ['vehicle_bodies.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('vehicle_year_model_attributes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_attribute_value_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_attribute_value_id'], ['vehicle_attribute_values.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_year_model_categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_category_id'], ['vehicle_categories.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_year_model_drive_trains',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_drive_train_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_drive_train_id'], ['vehicle_drive_trains.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_year_model_engines',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_engine_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_engine_id'], ['vehicle_engines.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_year_model_galleries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=True),
                    sa.Column('gallery_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gallery_item_id'], ['vehicle_gallery_items.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_year_model_infos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_info_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_info_id'], ['vehicle_infos.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_year_model_transmissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_year_model_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_transmission_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_transmission_id'], ['vehicle_transmissions.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_year_model_id'], ['vehicle_year_models.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('zip_codes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('code', sa.Integer(), nullable=True),
                    sa.Column('lat', sa.Float(), nullable=True),
                    sa.Column('long', sa.Float(), nullable=True),
                    sa.Column('city_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('code')
                    )
    op.create_table('price_vehicle_model_style_assignments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('value_in_cent', sa.Integer(), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('region_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_model_style_attributes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_attribute_value_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_attribute_value_id'], ['vehicle_attribute_values.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_model_style_drive_trains',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_drive_train_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_drive_train_id'], ['vehicle_drive_trains.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_model_style_engines',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_engine_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_engine_id'], ['vehicle_engines.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_model_style_galleries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=True),
                    sa.Column('gallery_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gallery_item_id'], ['vehicle_gallery_items.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_model_style_infos',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_info_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_info_id'], ['vehicle_infos.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_model_style_option_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_option_item_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_option_item_id'], ['vehicle_option_items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_model_style_transmissions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_transmission_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_transmission_id'], ['vehicle_transmissions.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('description', sa.String(), nullable=True),
                    sa.Column('is_pre_owned', sa.Boolean(), nullable=True),
                    sa.Column('vehicle_brand_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_model_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_model_style_id', sa.Integer(), nullable=False),
                    sa.Column('current_owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['current_owner_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_brand_id'], ['vehicle_brands.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_id'], ['vehicle_models.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_model_style_id'], ['vehicle_model_styles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('price_vehicle_assignments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('start_date', sa.DateTime(), nullable=False),
                    sa.Column('end_date', sa.DateTime(), nullable=True),
                    sa.Column('value_in_cent', sa.Integer(), nullable=True),
                    sa.Column('vehicle_id', sa.Integer(), nullable=False),
                    sa.Column('region_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_custom_attributes',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_attribute_value_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_attribute_value_id'], ['vehicle_attribute_values.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_custom_option_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_option_item_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_option_item_id'], ['vehicle_option_items.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_galleries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_id', sa.Integer(), nullable=True),
                    sa.Column('gallery_item_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gallery_item_id'], ['vehicle_gallery_items.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_histories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('vehicle_id', sa.Integer(), nullable=False),
                    sa.Column('purchased_date', sa.DateTime(), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('vehicle_statuses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('checked_date', sa.DateTime(), nullable=False),
                    sa.Column('mileage', sa.Float(), nullable=False),
                    sa.Column('note', sa.Text(), nullable=True),
                    sa.Column('vehicle_history_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['vehicle_history_id'], ['vehicle_histories.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_statuses')
    op.drop_table('vehicle_histories')
    op.drop_table('vehicle_galleries')
    op.drop_table('vehicle_custom_option_items')
    op.drop_table('vehicle_custom_attributes')
    op.drop_table('price_vehicle_assignments')
    op.drop_table('vehicles')
    op.drop_table('vehicle_model_style_transmissions')
    op.drop_table('vehicle_model_style_option_items')
    op.drop_table('vehicle_model_style_infos')
    op.drop_table('vehicle_model_style_galleries')
    op.drop_table('vehicle_model_style_engines')
    op.drop_table('vehicle_model_style_drive_trains')
    op.drop_table('vehicle_model_style_attributes')
    op.drop_table('price_vehicle_model_style_assignments')
    op.drop_table('zip_codes')
    op.drop_table('vehicle_year_model_transmissions')
    op.drop_table('vehicle_year_model_infos')
    op.drop_table('vehicle_year_model_galleries')
    op.drop_table('vehicle_year_model_engines')
    op.drop_table('vehicle_year_model_drive_trains')
    op.drop_table('vehicle_year_model_categories')
    op.drop_table('vehicle_year_model_attributes')
    op.drop_table('vehicle_model_styles')
    op.drop_table('addresses')
    op.drop_table('vehicle_year_models')
    op.drop_table('vehicle_model_galleries')
    op.drop_table('sessions')
    op.drop_table('reset_tokens')
    op.drop_table('cities')
    op.drop_table('vehicle_warranties')
    op.drop_table('vehicle_option_item_galleries')
    op.drop_table('vehicle_models')
    op.drop_table('vehicle_brand_galleries')
    op.drop_table('vehicle_attribute_values')
    op.drop_table('users')
    op.drop_table('states')
    op.drop_table('role_permissions')
    op.drop_table('price_option_assignments')
    op.drop_table('media_resources')
    op.drop_table('core_provider_i18n')
    op.drop_table('vehicle_transmissions')
    op.drop_table('vehicle_option_items')
    op.drop_table('vehicle_infos')
    op.drop_table('vehicle_gallery_items')
    op.drop_table('vehicle_engines')
    op.drop_table('vehicle_drive_trains')
    op.drop_table('vehicle_categories')
    op.drop_table('vehicle_brands')
    op.drop_table('vehicle_bodies')
    op.drop_table('vehicle_attributes')
    op.drop_table('tenants')
    op.drop_table('roles')
    op.drop_table('regions')
    op.drop_table('permissions')
    op.drop_table('media_providers')
    op.drop_table('locales')
    op.drop_table('countries')
    op.drop_table('core_provider_i18n_links')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
