"""add more fields to dealer

Revision ID: 79d7e26d0246
Revises: 7aa9953b40c1
Create Date: 2020-11-02 14:26:56.012446

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '79d7e26d0246'
down_revision = '7aa9953b40c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dealers', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('dealers', sa.Column('long', sa.Float(), nullable=True))
    op.add_column('dealers', sa.Column('phone', sa.String(length=128), nullable=True))
    op.create_unique_constraint('dealer_phone_unique', 'dealers', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dealer_phone_unique', 'dealers', type_='unique')
    op.drop_column('dealers', 'phone')
    op.drop_column('dealers', 'long')
    op.drop_column('dealers', 'lat')
    # ### end Alembic commands ###
