"""add status to request

Revision ID: 7aa9953b40c1
Revises: aa3ab8da0248
Create Date: 2020-11-01 10:08:04.744209

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7aa9953b40c1'
down_revision = 'aa3ab8da0248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    requeststatus = sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', name='requeststatus')
    requeststatus.create(connection)
    op.add_column('dealer_requests', sa.Column('status', sa.Enum(name='requeststatus'), nullable=True))
    op.add_column('requester_addresses', sa.Column('dealer_request_id', sa.Integer(), nullable=True))
    op.create_foreign_key('requester_addresses_requests', 'requester_addresses', 'dealer_requests',
                          ['dealer_request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('requester_addresses_requests', 'requester_addresses', type_='foreignkey')
    op.drop_column('requester_addresses', 'dealer_request_id')
    op.drop_column('dealer_requests', 'status')
    op.execute('DROP TYPE requeststatus')
    # ### end Alembic commands ###
