"""add dealer scheduler

Revision ID: 927915c0ad8a
Revises: 3a2322ff2503
Create Date: 2020-10-28 21:48:20.571758

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '927915c0ad8a'
down_revision = '3a2322ff2503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('name', sa.String(length=512), nullable=True),
                    sa.Column('website', sa.String(length=1024), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    sa.UniqueConstraint('website')
                    )
    op.create_table('dealer_addresses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('dealer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
                    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dealer_schedulers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('schedule_title', sa.String(length=512), nullable=True),
                    sa.Column('schedule_time', sa.DateTime(), nullable=False),
                    sa.Column('schedule_note', sa.Text(), nullable=True),
                    sa.Column('vehicle_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('dealer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealer_schedulers')
    op.drop_table('dealer_addresses')
    op.drop_table('dealers')
    # ### end Alembic commands ###
