"""init dealer requester

Revision ID: aa3ab8da0248
Revises: 927915c0ad8a
Create Date: 2020-10-31 15:51:11.093304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa3ab8da0248'
down_revision = '927915c0ad8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requester_addresses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('address_id', sa.Integer(), nullable=True),
                    sa.Column('dealer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
                    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('dealer_requests',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('modification_date', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=True),
                    sa.Column('requester_email', sa.String(length=128), nullable=True),
                    sa.Column('requester_phone_number', sa.String(length=32), nullable=False),
                    sa.Column('vehicle_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('pricing_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('credit_information', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('dealer_option', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('dealer_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dealer_requests')
    op.drop_table('requester_addresses')
    # ### end Alembic commands ###
